name: attendance
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^0.16.0
  google_sign_in: ^4.4.4
  firebase_core: ^0.4.0+9
  firebase_database: ^3.1.5
  firebase_storage: ^3.1.5
  http: ^0.12.0+2
  dio: ^3.0.9
  path_provider: ^1.6.5
  permission_handler: ^5.0.0+hotfix.3
  connectivity: ^0.4.8+2
  fluttertoast: ^4.0.1
  flutter_offline: "^0.3.0"
  url_launcher: ^5.4.10
  open_file: ^3.0.1
  flutter_swiper: ^1.1.6
  app_settings: ^4.0.0
  store_redirect: ^1.0.2
  carousel_slider: ^2.0.0
  flutter_spinkit: ^3.1.0

  flutter_html_to_pdf: ^0.5.2

  gradient_widgets: ^0.5.2
  animated_text_kit: ^2.0.1
  flutter_launcher_icons: ^0.7.5
  flutter_native_splash: ^0.1.9

  contacts_service: ^0.4.6

  file_picker: ^1.9.0+1
  spreadsheet_decoder: ^1.1.0
  grouped_buttons: ^1.0.4

  intl: ^0.16.1
 

  cupertino_icons: ^0.1.2

  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/

 